from __future__ import annotations

import argparse
import json
import os
import socket
import sys
import time
from datetime import datetime, timezone
from html import escape
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

from .network_scanner import (
    assess_risk,
    fingerprint_service,
    parse_port_spec,
    scan_hosts,
    scan_ports,
    vulnerability_hints,
)
from .system_info import collect_system_info


BANNER = r"""
  ____            _   _      _     ____                  _
 / ___| _   _ ___| \ | | ___| |_  / ___|  ___ ___  _   _| |_
 \___ \| | | / __|  \| |/ _ \ __| \___ \ / __/ _ \| | | | __|
  ___) | |_| \__ \ |\  |  __/ |_   ___) | (_| (_) | |_| | |_
 |____/ \__, |___/_| \_|\___|\__| |____/ \___\___/ \__,_|\__|
        |___/

SysNet Scout v0.3.0
Made by GitHub user pinkythegawd (MikePinku)
""".strip()


TOP_COMMON_PORTS = [
    21, 22, 23, 25, 53, 67, 68, 69, 80, 110, 111, 119, 123, 135, 137, 138, 139,
    143, 161, 162, 389, 443, 445, 465, 500, 514, 515, 520, 587, 631, 636, 873,
    902, 989, 990, 993, 995, 1080, 1194, 1433, 1434, 1521, 1723, 1812, 1813,
    1883, 2049, 2082, 2083, 2086, 2087, 2095, 2096, 2181, 2375, 2376, 3306, 3389,
    3478, 3690, 4369, 5060, 5061, 5432, 5672, 5900, 5985, 5986, 6379, 6443, 6667,
    6881, 8000, 8008, 8080, 8081, 8086, 8088, 8090, 8125, 8333, 8443, 8888, 9000,
    9042, 9092, 9200, 9300, 9418, 9999, 10000, 11211, 15672, 27017, 28017, 49152,
    49153, 49154, 50000, 50070, 50075, 50090, 61616, 65535,
]


WEB_PROFILE_PORTS = [80, 443, 8000, 8080, 8081, 8443, 3000]


class _Color:
    CYAN = "\033[96m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    MAGENTA = "\033[95m"
    BOLD = "\033[1m"
    RESET = "\033[0m"


def _enable_windows_ansi() -> None:
    if os.name != "nt":
        return
    try:
        import ctypes

        kernel32 = ctypes.windll.kernel32
        handle = kernel32.GetStdHandle(-11)
        mode = ctypes.c_ulong()
        if kernel32.GetConsoleMode(handle, ctypes.byref(mode)):
            kernel32.SetConsoleMode(handle, mode.value | 0x0004)
    except Exception:
        return


def _supports_color(no_color: bool) -> bool:
    if no_color or os.getenv("NO_COLOR"):
        return False
    return bool(getattr(sys.stdout, "isatty", lambda: False)())


def _supports_progress(no_progress: bool) -> bool:
    if no_progress:
        return False
    return bool(getattr(sys.stdout, "isatty", lambda: False)())


def _paint(text: str, color_code: str, enabled: bool) -> str:
    if not enabled:
        return text
    return f"{color_code}{text}{_Color.RESET}"


def _should_emit_json(json_flag: bool, output_path: str | None) -> bool:
    if json_flag:
        return True
    if not output_path:
        return False
    return output_path.lower().endswith(".json")


def _to_text_block(data: Dict[str, Any]) -> str:
    width = max(len(key) for key in data.keys()) if data else 0
    lines: List[str] = []
    for key, value in data.items():
        if isinstance(value, (list, dict)):
            value_text = json.dumps(value, ensure_ascii=True)
        else:
            value_text = str(value)
        lines.append(f"{key.ljust(width)} : {value_text}")
    return "\n".join(lines)


def _render_html_report(title: str, payload: Dict[str, Any]) -> str:
    pretty = escape(json.dumps(payload, indent=2, ensure_ascii=True))
    return (
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        f"  <title>{escape(title)} - SysNet Scout</title>\n"
        "  <style>\n"
        "    body{font-family:Consolas,Monaco,monospace;background:#0f1220;color:#e6edf3;padding:24px;}\n"
        "    .card{max-width:980px;margin:0 auto;background:#161b2e;border:1px solid #2b3558;border-radius:12px;padding:20px;}\n"
        "    h1{margin:0 0 8px 0;color:#7ee787;}\n"
        "    p{margin:0 0 16px 0;color:#9fb0d1;}\n"
        "    pre{background:#0b1020;padding:14px;border-radius:10px;overflow:auto;border:1px solid #223057;}\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "  <div class=\"card\">\n"
        f"    <h1>{escape(title)}</h1>\n"
        "    <p>Generated by SysNet Scout</p>\n"
        f"    <pre>{pretty}</pre>\n"
        "  </div>\n"
        "</body>\n"
        "</html>\n"
    )


def _export_report(save_path: str | None, title: str, payload: Dict[str, Any], text_body: str) -> None:
    if not save_path:
        return
    path = Path(save_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    ext = path.suffix.lower()

    if ext == ".json":
        body = json.dumps(payload, indent=2, ensure_ascii=True) + "\n"
    elif ext in (".html", ".htm"):
        body = _render_html_report(title=title, payload=payload)
    else:
        body = text_body + "\n"

    path.write_text(body, encoding="utf-8")


def _print_kv(data: Dict[str, Any], color: bool) -> str:
    block = _to_text_block(data)
    print(_paint(block, _Color.CYAN, color))
    return block


def _make_progress_callback(title: str, color: bool, enabled: bool) -> Optional[Callable[[int, int], None]]:
    if not enabled:
        return None

    def _callback(done: int, total: int) -> None:
        ratio = 0.0 if total <= 0 else done / total
        width = 24
        filled = int(ratio * width)
        bar = "#" * filled + "-" * (width - filled)
        percent = int(ratio * 100)
        line = f"\r{title} [{bar}] {done}/{total} {percent}%"
        print(_paint(line, _Color.YELLOW, color), end="", flush=True)
        if done >= total:
            print()

    return _callback


def _profile_defaults(profile: str) -> Tuple[List[int], float, int]:
    if profile == "quick":
        return sorted(TOP_COMMON_PORTS[:20]), 0.3, 256
    if profile == "web":
        return sorted(WEB_PROFILE_PORTS), 0.4, 128
    if profile == "full":
        return list(range(1, 1025)), 0.5, 320
    raise ValueError(f"Unknown profile: {profile}")


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _parse_timestamp(value: Any) -> Optional[datetime]:
    if not isinstance(value, str) or not value.strip():
        return None
    text = value.strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(text)
        if dt.tzinfo is None:
            return dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc)
    except ValueError:
        return None


def _resolve_target(target: str) -> Dict[str, Any]:
    ips: List[str] = []
    aliases: List[str] = []
    reverse_host = "unknown"

    try:
        host, aliases, ips = socket.gethostbyname_ex(target)
        if host:
            reverse_host = host
    except OSError:
        pass

    try:
        reverse_host = socket.gethostbyaddr(target)[0]
    except OSError:
        pass

    return {
        "target": target,
        "aliases": sorted(set(aliases)),
        "resolved_ips": sorted(set(ips)),
        "reverse_lookup": reverse_host,
    }


def _resolve_port_scan_config(
    ports_arg: str | None,
    top: int | None,
    profile: str | None,
    timeout_s: float | None,
    workers: int | None,
) -> Tuple[List[int], float, int, str]:
    profile_name = profile or "custom"
    default_timeout = 0.5
    default_workers = 256

    if ports_arg:
        ports = parse_port_spec(ports_arg)
    elif top:
        ports = sorted(TOP_COMMON_PORTS[:top])
    elif profile:
        ports, default_timeout, default_workers = _profile_defaults(profile)
    else:
        raise ValueError("Choose one port source: --ports, --top, or --profile")

    final_timeout = max(0.05, timeout_s if timeout_s is not None else default_timeout)
    final_workers = max(1, workers if workers is not None else default_workers)
    return ports, final_timeout, final_workers, profile_name


def _cmd_info(as_json: bool, no_color: bool, save: str | None) -> int:
    color = _supports_color(no_color)
    info = collect_system_info()
    started = time.perf_counter()
    info["duration_ms"] = f"{(time.perf_counter() - started) * 1000:.2f}"

    text_body = _to_text_block(info)
    if as_json:
        print(json.dumps(info, indent=2, ensure_ascii=True))
    else:
        print(_paint(BANNER, _Color.MAGENTA + _Color.BOLD, color))
        print()
        _print_kv(info, color=color)

    _export_report(save_path=save, title="System Information", payload=info, text_body=text_body)
    return 0


def _cmd_scan_hosts(
    cidr: str,
    timeout_ms: int,
    workers: int,
    as_json: bool,
    no_color: bool,
    no_progress: bool,
    save: str | None,
) -> int:
    color = _supports_color(no_color)
    progress = _make_progress_callback(
        title="Host scan",
        color=color,
        enabled=not as_json and _supports_progress(no_progress),
    )

    started = time.perf_counter()
    alive = scan_hosts(
        cidr=cidr,
        timeout_ms=timeout_ms,
        workers=workers,
        progress_callback=progress,
    )

    payload: Dict[str, Any] = {
        "target": cidr,
        "alive_hosts": alive,
        "count": len(alive),
        "timestamp": _utc_now_iso(),
        "duration_ms": round((time.perf_counter() - started) * 1000, 2),
    }

    plain_lines = [
        f"Target network : {cidr}",
        f"Alive hosts    : {len(alive)}",
        f"Duration (ms)  : {payload['duration_ms']}",
    ]
    for host in alive:
        plain_lines.append(f" - {host}")
    text_body = "\n".join(plain_lines)

    if as_json:
        print(json.dumps(payload, indent=2, ensure_ascii=True))
    else:
        print(_paint(BANNER, _Color.MAGENTA + _Color.BOLD, color))
        print()
        print(_paint(f"Target network : {cidr}", _Color.CYAN, color))
        print(_paint(f"Alive hosts    : {len(alive)}", _Color.GREEN, color))
        print(_paint(f"Duration (ms)  : {payload['duration_ms']}", _Color.YELLOW, color))
        for host in alive:
            print(_paint(f" - {host}", _Color.GREEN, color))

    _export_report(save_path=save, title="Host Scan", payload=payload, text_body=text_body)
    return 0


def _cmd_scan_ports(
    host: str,
    ports_arg: str | None,
    top: int | None,
    profile: str | None,
    timeout_s: float | None,
    workers: int | None,
    fingerprint: bool,
    hints: bool,
    as_json: bool,
    no_color: bool,
    no_progress: bool,
    save: str | None,
) -> int:
    color = _supports_color(no_color)
    ports, final_timeout, final_workers, profile_name = _resolve_port_scan_config(
        ports_arg=ports_arg,
        top=top,
        profile=profile,
        timeout_s=timeout_s,
        workers=workers,
    )

    progress = _make_progress_callback(
        title="Port scan",
        color=color,
        enabled=not as_json and _supports_progress(no_progress),
    )

    started = time.perf_counter()
    open_ports = scan_ports(
        host=host,
        ports=ports,
        timeout_s=final_timeout,
        workers=final_workers,
        progress_callback=progress,
    )

    if fingerprint:
        for item in open_ports:
            try:
                port_int = int(item.get("port", "0"))
            except ValueError:
                continue
            banner = fingerprint_service(host=host, port=port_int, timeout_s=min(1.2, final_timeout + 0.4))
            if banner:
                item["banner"] = banner

    hint_items = vulnerability_hints(open_ports) if hints else []
    risk = assess_risk(open_ports, hint_items)

    payload: Dict[str, Any] = {
        "target": host,
        "profile": profile_name,
        "scanned_port_count": len(ports),
        "fingerprinting": fingerprint,
        "hints_enabled": hints,
        "open_ports": open_ports,
        "count": len(open_ports),
        "hints": hint_items,
        "risk": risk,
        "timestamp": _utc_now_iso(),
        "duration_ms": round((time.perf_counter() - started) * 1000, 2),
    }

    plain_lines = [
        f"Target host      : {host}",
        f"Profile          : {profile_name}",
        f"Ports scanned    : {len(ports)}",
        f"Open ports       : {len(open_ports)}",
        f"Risk score       : {risk['score']} ({risk['level']})",
        f"Duration (ms)    : {payload['duration_ms']}",
    ]
    if hints and hint_items:
        plain_lines.append("Hints:")
        for hint in hint_items:
            plain_lines.append(f" - {hint}")
    for item in open_ports:
        plain_lines.append(f" - {item['port']}/tcp ({item['service']})")
    text_body = "\n".join(plain_lines)

    if as_json:
        print(json.dumps(payload, indent=2, ensure_ascii=True))
    else:
        print(_paint(BANNER, _Color.MAGENTA + _Color.BOLD, color))
        print()
        print(_paint(f"Target host      : {host}", _Color.CYAN, color))
        print(_paint(f"Profile          : {profile_name}", _Color.CYAN, color))
        print(_paint(f"Ports scanned    : {len(ports)}", _Color.CYAN, color))
        print(_paint(f"Open ports       : {len(open_ports)}", _Color.GREEN, color))
        print(_paint(f"Risk score       : {risk['score']} ({risk['level']})", _Color.YELLOW, color))
        print(_paint(f"Duration (ms)    : {payload['duration_ms']}", _Color.YELLOW, color))
        for item in open_ports:
            line = f" - {item['port']}/tcp ({item['service']})"
            if item.get("banner"):
                line += f" -> {item['banner']}"
            print(_paint(line, _Color.GREEN, color))
        if hints and hint_items:
            print(_paint("Hints:", _Color.YELLOW, color))
            for hint in hint_items:
                print(_paint(f" - {hint}", _Color.YELLOW, color))
        if risk.get("reasons"):
            print(_paint("Risk reasons:", _Color.YELLOW, color))
            for reason in risk["reasons"]:
                print(_paint(f" - {reason}", _Color.YELLOW, color))

    _export_report(save_path=save, title="Port Scan", payload=payload, text_body=text_body)
    return 0


def _cmd_resolve(target: str, as_json: bool, no_color: bool, save: str | None) -> int:
    color = _supports_color(no_color)
    payload = _resolve_target(target)
    text_body = _to_text_block(
        {
            "target": str(payload["target"]),
            "reverse_lookup": str(payload["reverse_lookup"]),
            "aliases": ", ".join(payload["aliases"]) or "none",
            "resolved_ips": ", ".join(payload["resolved_ips"]) or "none",
        }
    )

    if as_json:
        print(json.dumps(payload, indent=2, ensure_ascii=True))
    else:
        print(_paint(BANNER, _Color.MAGENTA + _Color.BOLD, color))
        print()
        _print_kv(
            {
                "target": str(payload["target"]),
                "reverse_lookup": str(payload["reverse_lookup"]),
                "aliases": ", ".join(payload["aliases"]) or "none",
                "resolved_ips": ", ".join(payload["resolved_ips"]) or "none",
            },
            color=color,
        )

    _export_report(save_path=save, title="Resolve", payload=payload, text_body=text_body)
    return 0


def _load_json_file(path: str) -> Dict[str, Any]:
    data = json.loads(Path(path).read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict):
        raise ValueError(f"JSON file must contain an object: {path}")
    return data


def _compare_payloads(baseline: Dict[str, Any], current: Dict[str, Any]) -> Dict[str, Any]:
    if "alive_hosts" in baseline and "alive_hosts" in current:
        old_hosts = set(str(h) for h in baseline.get("alive_hosts", []))
        new_hosts = set(str(h) for h in current.get("alive_hosts", []))
        return {
            "type": "host-scan",
            "added_hosts": sorted(new_hosts - old_hosts),
            "removed_hosts": sorted(old_hosts - new_hosts),
            "added_count": len(new_hosts - old_hosts),
            "removed_count": len(old_hosts - new_hosts),
        }

    if "open_ports" in baseline and "open_ports" in current:
        old_ports = set(str(item.get("port")) for item in baseline.get("open_ports", []))
        new_ports = set(str(item.get("port")) for item in current.get("open_ports", []))
        return {
            "type": "port-scan",
            "added_ports": sorted(new_ports - old_ports, key=lambda x: int(x)),
            "removed_ports": sorted(old_ports - new_ports, key=lambda x: int(x)),
            "added_count": len(new_ports - old_ports),
            "removed_count": len(old_ports - new_ports),
        }

    changed_fields: Dict[str, Dict[str, Any]] = {}
    for key in sorted(set(baseline.keys()) | set(current.keys())):
        if baseline.get(key) != current.get(key):
            changed_fields[key] = {
                "baseline": baseline.get(key),
                "current": current.get(key),
            }

    return {
        "type": "generic",
        "changed_fields": changed_fields,
        "changed_count": len(changed_fields),
    }


def _cmd_compare(
    baseline_path: str,
    current_path: str,
    as_json: bool,
    no_color: bool,
    save: str | None,
) -> int:
    color = _supports_color(no_color)
    baseline = _load_json_file(baseline_path)
    current = _load_json_file(current_path)
    payload = _compare_payloads(baseline, current)
    payload["baseline_file"] = baseline_path
    payload["current_file"] = current_path

    text_body = _to_text_block(payload)
    if as_json:
        print(json.dumps(payload, indent=2, ensure_ascii=True))
    else:
        print(_paint(BANNER, _Color.MAGENTA + _Color.BOLD, color))
        print()
        _print_kv(payload, color=color)

    _export_report(save_path=save, title="Compare Scan Results", payload=payload, text_body=text_body)
    return 0


def _risk_summary_from_report(report: Dict[str, Any]) -> Dict[str, Any]:
    target = str(report.get("target", "unknown"))
    open_ports = report.get("open_ports", [])
    hints = report.get("hints", [])

    if isinstance(report.get("risk"), dict):
        risk = {
            "score": int(report["risk"].get("score", 0)),
            "level": str(report["risk"].get("level", "low")),
            "reasons": list(report["risk"].get("reasons", [])),
        }
    else:
        risk = assess_risk(
            open_port_items=open_ports if isinstance(open_ports, list) else [],
            hint_items=hints if isinstance(hints, list) else [],
        )

    return {
        "target": target,
        "open_port_count": len(open_ports) if isinstance(open_ports, list) else 0,
        "risk": risk,
    }


def _cmd_risk(report_path: str, as_json: bool, no_color: bool, save: str | None) -> int:
    color = _supports_color(no_color)
    report = _load_json_file(report_path)
    summary = _risk_summary_from_report(report)
    payload: Dict[str, Any] = {
        "report_file": report_path,
        "target": summary["target"],
        "open_port_count": summary["open_port_count"],
        "risk": summary["risk"],
    }

    plain_lines = [
        f"Report file      : {report_path}",
        f"Target           : {payload['target']}",
        f"Open port count  : {payload['open_port_count']}",
        f"Risk score       : {payload['risk']['score']} ({payload['risk']['level']})",
    ]
    reasons = payload["risk"].get("reasons", [])
    if reasons:
        plain_lines.append("Risk reasons:")
        for reason in reasons:
            plain_lines.append(f" - {reason}")
    text_body = "\n".join(plain_lines)

    if as_json:
        print(json.dumps(payload, indent=2, ensure_ascii=True))
    else:
        print(_paint(BANNER, _Color.MAGENTA + _Color.BOLD, color))
        print()
        print(_paint(f"Report file      : {report_path}", _Color.CYAN, color))
        print(_paint(f"Target           : {payload['target']}", _Color.CYAN, color))
        print(_paint(f"Open port count  : {payload['open_port_count']}", _Color.CYAN, color))
        print(_paint(f"Risk score       : {payload['risk']['score']} ({payload['risk']['level']})", _Color.YELLOW, color))
        if reasons:
            print(_paint("Risk reasons:", _Color.YELLOW, color))
            for reason in reasons:
                print(_paint(f" - {reason}", _Color.YELLOW, color))

    _export_report(save_path=save, title="Risk Summary", payload=payload, text_body=text_body)
    return 0


def _cmd_risk_trend(report_paths: List[str], as_json: bool, no_color: bool, save: str | None) -> int:
    color = _supports_color(no_color)
    snapshots: List[Dict[str, Any]] = []

    for index, report_path in enumerate(report_paths):
        report = _load_json_file(report_path)
        summary = _risk_summary_from_report(report)
        timestamp_raw = report.get("timestamp")
        timestamp_obj = _parse_timestamp(timestamp_raw)
        snapshots.append(
            {
                "input_index": index,
                "report_file": report_path,
                "target": summary["target"],
                "open_port_count": summary["open_port_count"],
                "score": int(summary["risk"]["score"]),
                "level": str(summary["risk"]["level"]),
                "timestamp": timestamp_raw if isinstance(timestamp_raw, str) else "",
                "_timestamp_obj": timestamp_obj,
            }
        )

    snapshots.sort(
        key=lambda item: (
            item["_timestamp_obj"] is None,
            item["_timestamp_obj"] or datetime.max.replace(tzinfo=timezone.utc),
            item["input_index"],
        )
    )

    for item in snapshots:
        item.pop("_timestamp_obj", None)
        item.pop("input_index", None)

    first_score = int(snapshots[0]["score"]) if snapshots else 0
    last_score = int(snapshots[-1]["score"]) if snapshots else 0
    delta = last_score - first_score

    if delta > 0:
        trend = "worse"
    elif delta < 0:
        trend = "improved"
    else:
        trend = "stable"

    payload: Dict[str, Any] = {
        "report_count": len(snapshots),
        "trend": trend,
        "score_delta": delta,
        "start_score": first_score,
        "end_score": last_score,
        "max_score": max((int(item["score"]) for item in snapshots), default=0),
        "snapshots": snapshots,
    }

    plain_lines = [
        f"Report count     : {payload['report_count']}",
        f"Trend            : {payload['trend']}",
        f"Score delta      : {payload['score_delta']}",
        f"Start score      : {payload['start_score']}",
        f"End score        : {payload['end_score']}",
        f"Max score        : {payload['max_score']}",
        "Snapshots:",
    ]
    for item in snapshots:
        plain_lines.append(
            f" - {item['report_file']}: score={item['score']} level={item['level']} target={item['target']} timestamp={item['timestamp'] or 'n/a'}"
        )
    text_body = "\n".join(plain_lines)

    if as_json:
        print(json.dumps(payload, indent=2, ensure_ascii=True))
    else:
        print(_paint(BANNER, _Color.MAGENTA + _Color.BOLD, color))
        print()
        print(_paint(f"Report count     : {payload['report_count']}", _Color.CYAN, color))
        print(_paint(f"Trend            : {payload['trend']}", _Color.YELLOW, color))
        print(_paint(f"Score delta      : {payload['score_delta']}", _Color.CYAN, color))
        print(_paint(f"Start score      : {payload['start_score']}", _Color.CYAN, color))
        print(_paint(f"End score        : {payload['end_score']}", _Color.CYAN, color))
        print(_paint(f"Max score        : {payload['max_score']}", _Color.CYAN, color))
        print(_paint("Snapshots:", _Color.YELLOW, color))
        for item in snapshots:
            line = f" - {item['report_file']}: score={item['score']} level={item['level']} target={item['target']} timestamp={item['timestamp'] or 'n/a'}"
            print(_paint(line, _Color.CYAN, color))

    _export_report(save_path=save, title="Risk Trend", payload=payload, text_body=text_body)
    return 0


def _prompt(prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default is not None else ""
    value = input(f"{prompt}{suffix}: ").strip()
    if value:
        return value
    return default or ""


def _prompt_bool(prompt: str, default: bool = False) -> bool:
    default_text = "Y/n" if default else "y/N"
    value = input(f"{prompt} ({default_text}): ").strip().lower()
    if not value:
        return default
    return value in {"y", "yes", "1", "true"}


def _cmd_start(
    choice: str | None,
    as_json: bool,
    no_color: bool,
    no_progress: bool,
    save: str | None,
) -> int:
    if not choice:
        if not getattr(sys.stdin, "isatty", lambda: False)():
            raise ValueError("Interactive mode requires a TTY. Use --choice for non-interactive usage.")

        print(BANNER)
        print()
        print("Quick Start Menu")
        print("  1) info")
        print("  2) scan-hosts")
        print("  3) scan-ports")
        print("  4) resolve")
        print("  5) risk")
        print("  6) risk-trend")
        raw = _prompt("Select option", "1").lower()
        choice_map = {
            "1": "info",
            "2": "scan-hosts",
            "3": "scan-ports",
            "4": "resolve",
            "5": "risk",
            "6": "risk-trend",
        }
        choice = choice_map.get(raw, raw)

    if choice == "info":
        return _cmd_info(as_json=as_json, no_color=no_color, save=save)

    if choice == "scan-hosts":
        cidr = _prompt("CIDR target", "192.168.1.0/24")
        timeout_ms = int(_prompt("Timeout in ms", "1000"))
        workers = int(_prompt("Worker threads", "64"))
        return _cmd_scan_hosts(
            cidr=cidr,
            timeout_ms=max(1, timeout_ms),
            workers=max(1, workers),
            as_json=as_json,
            no_color=no_color,
            no_progress=no_progress,
            save=save,
        )

    if choice == "scan-ports":
        host = _prompt("Target host", "127.0.0.1")
        mode = _prompt("Mode (profile/ports/top)", "profile").lower()
        profile: str | None = None
        ports_arg: str | None = None
        top: int | None = None

        if mode == "ports":
            ports_arg = _prompt("Ports spec", "22,80,443")
        elif mode == "top":
            top = int(_prompt("Top preset (20 or 100)", "20"))
        else:
            profile = _prompt("Profile (quick/web/full)", "web")

        fingerprint = _prompt_bool("Enable fingerprinting", default=True)
        hints = _prompt_bool("Enable risk hints", default=True)

        return _cmd_scan_ports(
            host=host,
            ports_arg=ports_arg,
            top=top,
            profile=profile,
            timeout_s=None,
            workers=None,
            fingerprint=fingerprint,
            hints=hints,
            as_json=as_json,
            no_color=no_color,
            no_progress=no_progress,
            save=save,
        )

    if choice == "resolve":
        target = _prompt("Target domain/IP", "example.com")
        return _cmd_resolve(target=target, as_json=as_json, no_color=no_color, save=save)

    if choice == "risk":
        report_path = _prompt("Path to report JSON", "reports/ports.json")
        return _cmd_risk(report_path=report_path, as_json=as_json, no_color=no_color, save=save)

    if choice == "risk-trend":
        reports_raw = _prompt("Report paths separated by space", "reports/ports_day1.json reports/ports_day2.json")
        report_paths = [item for item in reports_raw.split() if item]
        if not report_paths:
            raise ValueError("At least one report path is required for risk-trend.")
        return _cmd_risk_trend(report_paths=report_paths, as_json=as_json, no_color=no_color, save=save)

    raise ValueError(f"Unknown start choice: {choice}")


def _cmd_demo(as_json: bool, no_color: bool, no_progress: bool, save: str | None) -> int:
    color = _supports_color(no_color)
    reports_dir = Path("reports")
    reports_dir.mkdir(parents=True, exist_ok=True)

    host_target_a = "127.0.0.0/30"
    host_target_b = "127.0.0.0/31"
    port_target = "127.0.0.1"

    started = time.perf_counter()
    hosts_a = scan_hosts(host_target_a, timeout_ms=800, workers=8, progress_callback=_make_progress_callback("Demo host scan A", color, _supports_progress(no_progress) and not as_json))
    hosts_b = scan_hosts(host_target_b, timeout_ms=800, workers=8, progress_callback=_make_progress_callback("Demo host scan B", color, _supports_progress(no_progress) and not as_json))
    ports = _profile_defaults("web")[0]
    open_ports = scan_ports(
        host=port_target,
        ports=ports,
        timeout_s=0.4,
        workers=128,
        progress_callback=_make_progress_callback("Demo port scan", color, _supports_progress(no_progress) and not as_json),
    )
    hints = vulnerability_hints(open_ports)
    risk = assess_risk(open_ports, hints)

    hosts_a_payload: Dict[str, Any] = {
        "target": host_target_a,
        "alive_hosts": hosts_a,
        "count": len(hosts_a),
        "timestamp": _utc_now_iso(),
    }
    hosts_b_payload: Dict[str, Any] = {
        "target": host_target_b,
        "alive_hosts": hosts_b,
        "count": len(hosts_b),
        "timestamp": _utc_now_iso(),
    }
    ports_payload: Dict[str, Any] = {
        "target": port_target,
        "profile": "web",
        "scanned_port_count": len(ports),
        "open_ports": open_ports,
        "count": len(open_ports),
        "hints": hints,
        "risk": risk,
        "timestamp": _utc_now_iso(),
    }

    compare_payload = _compare_payloads(hosts_a_payload, hosts_b_payload)
    compare_payload["baseline_file"] = str(reports_dir / "demo_hosts_a.json")
    compare_payload["current_file"] = str(reports_dir / "demo_hosts_b.json")

    trend_payload = {
        "report_count": 2,
        "trend": "stable",
        "score_delta": 0,
        "start_score": int(risk["score"]),
        "end_score": int(risk["score"]),
        "max_score": int(risk["score"]),
        "snapshots": [
            {
                "report_file": str(reports_dir / "demo_ports_a.json"),
                "target": port_target,
                "open_port_count": len(open_ports),
                "score": int(risk["score"]),
                "level": str(risk["level"]),
                "timestamp": ports_payload["timestamp"],
            },
            {
                "report_file": str(reports_dir / "demo_ports_b.json"),
                "target": port_target,
                "open_port_count": len(open_ports),
                "score": int(risk["score"]),
                "level": str(risk["level"]),
                "timestamp": _utc_now_iso(),
            },
        ],
    }

    (reports_dir / "demo_hosts_a.json").write_text(json.dumps(hosts_a_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    (reports_dir / "demo_hosts_b.json").write_text(json.dumps(hosts_b_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    (reports_dir / "demo_ports_a.json").write_text(json.dumps(ports_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    (reports_dir / "demo_ports_b.json").write_text(json.dumps(ports_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    (reports_dir / "demo_compare.json").write_text(json.dumps(compare_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    (reports_dir / "demo_risk_trend.json").write_text(json.dumps(trend_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")

    dashboard_payload: Dict[str, Any] = {
        "mode": "demo",
        "generated_files": [
            str(reports_dir / "demo_hosts_a.json"),
            str(reports_dir / "demo_hosts_b.json"),
            str(reports_dir / "demo_ports_a.json"),
            str(reports_dir / "demo_ports_b.json"),
            str(reports_dir / "demo_compare.json"),
            str(reports_dir / "demo_risk_trend.json"),
            str(reports_dir / "demo_dashboard.html"),
        ],
        "summary": {
            "hosts_scan_a_count": len(hosts_a),
            "hosts_scan_b_count": len(hosts_b),
            "open_port_count": len(open_ports),
            "risk": risk,
            "duration_ms": round((time.perf_counter() - started) * 1000, 2),
        },
    }

    dashboard_html = _render_html_report("Demo Dashboard", dashboard_payload)
    (reports_dir / "demo_dashboard.html").write_text(dashboard_html, encoding="utf-8")

    text_body = _to_text_block(
        {
            "mode": "demo",
            "reports_dir": str(reports_dir),
            "hosts_scan_a_count": len(hosts_a),
            "hosts_scan_b_count": len(hosts_b),
            "open_port_count": len(open_ports),
            "risk_score": risk["score"],
            "risk_level": risk["level"],
            "duration_ms": dashboard_payload["summary"]["duration_ms"],
        }
    )

    if as_json:
        print(json.dumps(dashboard_payload, indent=2, ensure_ascii=True))
    else:
        print(_paint(BANNER, _Color.MAGENTA + _Color.BOLD, color))
        print()
        print(_paint("Demo mode completed. Generated artifacts:", _Color.YELLOW, color))
        for path in dashboard_payload["generated_files"]:
            print(_paint(f" - {path}", _Color.CYAN, color))
        print()
        print(_paint(text_body, _Color.CYAN, color))

    _export_report(save_path=save, title="Demo Mode", payload=dashboard_payload, text_body=text_body)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="sysnet-scout",
        description="Cross-platform system information and network scanner utility",
    )
    parser.add_argument("--no-color", action="store_true", help="Disable ANSI colors for non-JSON output")
    parser.add_argument("--no-progress", action="store_true", help="Disable progress bar for scans")
    subparsers = parser.add_subparsers(dest="command", required=True)

    info_parser = subparsers.add_parser("info", help="Show local system information")
    info_parser.add_argument("--json", action="store_true", help="Output in JSON format")
    info_parser.add_argument("--save", "--export", dest="save", help="Export output file path (.json/.txt/.html)")

    hosts_parser = subparsers.add_parser("scan-hosts", help="Ping sweep a CIDR network")
    hosts_parser.add_argument("--cidr", required=True, help="CIDR target, e.g. 192.168.1.0/24")
    hosts_parser.add_argument("--timeout", type=int, default=1000, help="Ping timeout in ms")
    hosts_parser.add_argument("--workers", type=int, default=64, help="Concurrent workers")
    hosts_parser.add_argument("--no-progress", dest="scan_no_progress", action="store_true", help="Disable progress bar")
    hosts_parser.add_argument("--json", action="store_true", help="Output in JSON format")
    hosts_parser.add_argument("--save", "--export", dest="save", help="Export output file path (.json/.txt/.html)")

    ports_parser = subparsers.add_parser("scan-ports", help="Scan TCP ports on a host")
    ports_parser.add_argument("--host", required=True, help="Target host or IPv4 address")
    port_mode = ports_parser.add_mutually_exclusive_group(required=True)
    port_mode.add_argument("--ports", help="Port list/range like 22,80,443 or 1-1024")
    port_mode.add_argument("--top", type=int, choices=[20, 100], help="Quick preset of top common ports")
    port_mode.add_argument("--profile", choices=["quick", "web", "full"], help="Scan profile preset")
    ports_parser.add_argument("--timeout", type=float, default=None, help="Socket timeout in seconds")
    ports_parser.add_argument("--workers", type=int, default=None, help="Concurrent workers")
    ports_parser.add_argument("--no-progress", dest="scan_no_progress", action="store_true", help="Disable progress bar")
    ports_parser.add_argument("--fingerprint", action="store_true", help="Attempt basic service banner fingerprinting")
    ports_parser.add_argument("--hints", action="store_true", help="Show informational security hardening hints")
    ports_parser.add_argument("--json", action="store_true", help="Output in JSON format")
    ports_parser.add_argument("--save", "--export", dest="save", help="Export output file path (.json/.txt/.html)")

    resolve_parser = subparsers.add_parser("resolve", help="Resolve hostname/IP and reverse DNS")
    resolve_parser.add_argument("--target", required=True, help="Domain or IP to resolve")
    resolve_parser.add_argument("--json", action="store_true", help="Output in JSON format")
    resolve_parser.add_argument("--save", "--export", dest="save", help="Export output file path (.json/.txt/.html)")

    compare_parser = subparsers.add_parser("compare", help="Compare two JSON scan result files")
    compare_parser.add_argument("--baseline", required=True, help="Baseline JSON report path")
    compare_parser.add_argument("--current", required=True, help="Current JSON report path")
    compare_parser.add_argument("--json", action="store_true", help="Output in JSON format")
    compare_parser.add_argument("--save", "--export", dest="save", help="Export output file path (.json/.txt/.html)")

    risk_parser = subparsers.add_parser("risk", help="Summarize risk from a saved JSON report")
    risk_parser.add_argument("--report", required=True, help="JSON report path from scan-ports")
    risk_parser.add_argument("--json", action="store_true", help="Output in JSON format")
    risk_parser.add_argument("--save", "--export", dest="save", help="Export output file path (.json/.txt/.html)")

    trend_parser = subparsers.add_parser("risk-trend", help="Analyze risk trend from multiple JSON reports")
    trend_parser.add_argument("--reports", nargs="+", required=True, help="Ordered list of JSON report paths")
    trend_parser.add_argument("--json", action="store_true", help="Output in JSON format")
    trend_parser.add_argument("--save", "--export", dest="save", help="Export output file path (.json/.txt/.html)")

    start_parser = subparsers.add_parser("start", help="Interactive quick-start menu")
    start_parser.add_argument(
        "--choice",
        choices=["info", "scan-hosts", "scan-ports", "resolve", "risk", "risk-trend"],
        help="Non-interactive mode: run a single menu choice directly",
    )
    start_parser.add_argument("--json", action="store_true", help="Output in JSON format")
    start_parser.add_argument("--save", "--export", dest="save", help="Export output file path (.json/.txt/.html)")

    demo_parser = subparsers.add_parser("demo", help="Generate a safe local demo with sample reports")
    demo_parser.add_argument("--json", action="store_true", help="Output in JSON format")
    demo_parser.add_argument("--save", "--export", dest="save", help="Export output file path (.json/.txt/.html)")

    return parser


def main(argv: List[str] | None = None) -> int:
    _enable_windows_ansi()
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        if args.command == "info":
            return _cmd_info(
                as_json=_should_emit_json(args.json, args.save),
                no_color=args.no_color,
                save=args.save,
            )
        if args.command == "scan-hosts":
            return _cmd_scan_hosts(
                cidr=args.cidr,
                timeout_ms=max(1, args.timeout),
                workers=max(1, args.workers),
                as_json=_should_emit_json(args.json, args.save),
                no_color=args.no_color,
                no_progress=bool(args.no_progress or getattr(args, "scan_no_progress", False)),
                save=args.save,
            )
        if args.command == "scan-ports":
            return _cmd_scan_ports(
                host=args.host,
                ports_arg=args.ports,
                top=args.top,
                profile=args.profile,
                timeout_s=args.timeout,
                workers=args.workers,
                fingerprint=args.fingerprint,
                hints=args.hints,
                as_json=_should_emit_json(args.json, args.save),
                no_color=args.no_color,
                no_progress=bool(args.no_progress or getattr(args, "scan_no_progress", False)),
                save=args.save,
            )
        if args.command == "resolve":
            return _cmd_resolve(
                target=args.target,
                as_json=_should_emit_json(args.json, args.save),
                no_color=args.no_color,
                save=args.save,
            )
        if args.command == "compare":
            return _cmd_compare(
                baseline_path=args.baseline,
                current_path=args.current,
                as_json=_should_emit_json(args.json, args.save),
                no_color=args.no_color,
                save=args.save,
            )
        if args.command == "risk":
            return _cmd_risk(
                report_path=args.report,
                as_json=_should_emit_json(args.json, args.save),
                no_color=args.no_color,
                save=args.save,
            )
        if args.command == "risk-trend":
            return _cmd_risk_trend(
                report_paths=args.reports,
                as_json=_should_emit_json(args.json, args.save),
                no_color=args.no_color,
                save=args.save,
            )
        if args.command == "start":
            return _cmd_start(
                choice=args.choice,
                as_json=_should_emit_json(args.json, args.save),
                no_color=args.no_color,
                no_progress=args.no_progress,
                save=args.save,
            )
        if args.command == "demo":
            return _cmd_demo(
                as_json=_should_emit_json(args.json, args.save),
                no_color=args.no_color,
                no_progress=args.no_progress,
                save=args.save,
            )
    except ValueError as exc:
        parser.error(str(exc))

    parser.error("Unknown command")
    return 2
